default_chain: stride-testnet
chains:
  gaia-testnet:
    key: royal_validator_key_gaia
    chain-id: GAIA
    rpc-addr: http://127.0.0.1:26677      # use your own GAIA RPC endpoint here
    grpc-addr: http://127.0.0.1:9097     # use your own GAIA GRPC endpoint here
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001uatom
    key-directory: /root/.icq/keys
    debug: true
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
  stride-testnet:
    key: royal_validator_key_stride
    chain-id: STRIDE-TESTNET-4
    rpc-addr: http://127.0.0.1:26667      # use your own Stride GRPC endpoint here
    grpc-addr: http://127.0.0.1:9096     # use your own Stride GRPC endpoint here
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 0.001ustrd
    key-directory: /root/.icq/keys
    debug: true
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
cl: {}
